name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: DigitalOcean - doctl
        uses: digitalocean/action-doctl@2.5.0
        with:
          token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: abspayd
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Docker buildx
