name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
        username: abspayd
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: abspayd/music-companion:latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.5.0
        with:
          token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

      - name: Docker pull and run
        run: echo "TODO"
