name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker
      uses: docker/login-action@v3.0.0
      with:
        username: abspayd
        password: $DOCKER_ACCESS_TOKEN
    - name: Build the Docker image
      run: make docker-export
